### PR TITLE
dev-rokers: Add network services

### PR DESCRIPTION
**Pull request by gmacario**
Fix https://github.com/robotrokers/genivi-dev-platform/issues/5

Signed-off-by: Gianpaolo Macario <gmacario@gmail.com>

### CODE REVIEW

**Comment by gmacario** [comment]
Excerpt from https://build.rokers.io/blue/organizations/jenkins/robotrokers%2Fgenivi-dev-platform/detail/PR-9/1/pipeline

```
...
NOTE: Running task 726 of 1931 (/var/jenkins_home/workspace/rs_genivi-dev-platform_PR-9-36W3EOEBNQW3C3NHVVX2BVMRTCK4WU7FZKFC6B42DZI3MMKCMZWQ/gdp-src-build/../poky/meta/recipes-connectivity/dhcp/dhcp_4.3.4.bb:do_fetch)
...
NOTE: recipe dhcp-4.3.4-r0: task do_fetch: Started
...
NOTE: recipe dhcp-4.3.4-r0: task do_fetch: Succeeded
NOTE: Running task 745 of 1931 (/var/jenkins_home/workspace/rs_genivi-dev-platform_PR-9-36W3EOEBNQW3C3NHVVX2BVMRTCK4WU7FZKFC6B42DZI3MMKCMZWQ/gdp-src-build/../poky/meta/recipes-connectivity/dhcp/dhcp_4.3.4.bb:do_unpack)
...
NOTE: recipe dhcp-4.3.4-r0: task do_unpack: Started
...
NOTE: recipe dhcp-4.3.4-r0: task do_unpack: Succeeded
NOTE: Running task 748 of 1931 (/var/jenkins_home/workspace/rs_genivi-dev-platform_PR-9-36W3EOEBNQW3C3NHVVX2BVMRTCK4WU7FZKFC6B42DZI3MMKCMZWQ/gdp-src-build/../poky/meta/recipes-connectivity/dhcp/dhcp_4.3.4.bb:do_patch)
...
NOTE: recipe dhcp-4.3.4-r0: task do_patch: Started
...
NOTE: recipe dhcp-4.3.4-r0: task do_patch: Succeeded
...
NOTE: Running task 913 of 1931 (/var/jenkins_home/workspace/rs_genivi-dev-platform_PR-9-36W3EOEBNQW3C3NHVVX2BVMRTCK4WU7FZKFC6B42DZI3MMKCMZWQ/gdp-src-build/../poky/meta/recipes-connectivity/dhcp/dhcp_4.3.4.bb:do_populate_lic)
...
NOTE: recipe dhcp-4.3.4-r0: task do_populate_lic: Started
NOTE: recipe gmp-native-6.1.1-r0: task do_populate_lic: Started
NOTE: recipe dhcp-4.3.4-r0: task do_populate_lic: Succeeded
...
NOTE: recipe dhcp-4.3.4-r0: task do_configure: Succeeded
...
NOTE: Running task 1731 of 1931 (/var/jenkins_home/workspace/rs_genivi-dev-platform_PR-9-36W3EOEBNQW3C3NHVVX2BVMRTCK4WU7FZKFC6B42DZI3MMKCMZWQ/gdp-src-build/../poky/meta/recipes-connectivity/dhcp/dhcp_4.3.4.bb:do_compile)
NOTE: recipe dhcp-4.3.4-r0: task do_compile: Started
...
NOTE: recipe dhcp-4.3.4-r0: task do_compile: Succeeded
NOTE: Running task 1736 of 1931 (/var/jenkins_home/workspace/rs_genivi-dev-platform_PR-9-36W3EOEBNQW3C3NHVVX2BVMRTCK4WU7FZKFC6B42DZI3MMKCMZWQ/gdp-src-build/../poky/meta/recipes-connectivity/dhcp/dhcp_4.3.4.bb:do_install)
NOTE: recipe dhcp-4.3.4-r0: task do_install: Started
NOTE: recipe dhcp-4.3.4-r0: task do_install: Succeeded
NOTE: Running task 1737 of 1931 (/var/jenkins_home/workspace/rs_genivi-dev-platform_PR-9-36W3EOEBNQW3C3NHVVX2BVMRTCK4WU7FZKFC6B42DZI3MMKCMZWQ/gdp-src-build/../poky/meta/recipes-connectivity/dhcp/dhcp_4.3.4.bb:do_package)
NOTE: recipe dhcp-4.3.4-r0: task do_package: Started
...
NOTE: recipe dhcp-4.3.4-r0: task do_package: Succeeded
...
NOTE: Running task 1754 of 1931 (/var/jenkins_home/workspace/rs_genivi-dev-platform_PR-9-36W3EOEBNQW3C3NHVVX2BVMRTCK4WU7FZKFC6B42DZI3MMKCMZWQ/gdp-src-build/../poky/meta/recipes-connectivity/dhcp/dhcp_4.3.4.bb:do_packagedata)
NOTE: recipe hostapd-2.5-r0: task do_package: Started
NOTE: recipe dhcp-4.3.4-r0: task do_packagedata: Started
...
NOTE: recipe dhcp-4.3.4-r0: task do_packagedata: Succeeded
...
NOTE: Running task 1789 of 1931 (/var/jenkins_home/workspace/rs_genivi-dev-platform_PR-9-36W3EOEBNQW3C3NHVVX2BVMRTCK4WU7FZKFC6B42DZI3MMKCMZWQ/gdp-src-build/../poky/meta/recipes-connectivity/dhcp/dhcp_4.3.4.bb:do_package_write_rpm)
NOTE: recipe dhcp-4.3.4-r0: task do_package_write_rpm: Started
...
NOTE: recipe dhcp-4.3.4-r0: task do_package_write_rpm: Succeeded
...
NOTE: Running task 1815 of 1931 (/var/jenkins_home/workspace/rs_genivi-dev-platform_PR-9-36W3EOEBNQW3C3NHVVX2BVMRTCK4WU7FZKFC6B42DZI3MMKCMZWQ/gdp-src-build/../poky/meta/recipes-connectivity/dhcp/dhcp_4.3.4.bb:do_package_qa)
NOTE: recipe dhcp-4.3.4-r0: task do_package_qa: Started
NOTE: recipe dhcp-4.3.4-r0: task do_package_qa: Succeeded
...
NOTE: Running task 1852 of 1931 (/var/jenkins_home/workspace/rs_genivi-dev-platform_PR-9-36W3EOEBNQW3C3NHVVX2BVMRTCK4WU7FZKFC6B42DZI3MMKCMZWQ/gdp-src-build/../poky/meta/recipes-connectivity/dhcp/dhcp_4.3.4.bb:do_package_write_ipk)
...
NOTE: recipe dhcp-4.3.4-r0: task do_package_write_ipk: Started
...
NOTE: Running task 1862 of 1931 (/var/jenkins_home/workspace/rs_genivi-dev-platform_PR-9-36W3EOEBNQW3C3NHVVX2BVMRTCK4WU7FZKFC6B42DZI3MMKCMZWQ/gdp-src-build/../poky/meta/recipes-connectivity/dhcp/dhcp_4.3.4.bb:do_populate_sysroot)
...
NOTE: recipe dhcp-4.3.4-r0: task do_populate_sysroot: Started
...
NOTE: recipe dhcp-4.3.4-r0: task do_populate_sysroot: Succeeded
...
NOTE: recipe dhcp-4.3.4-r0: task do_package_write_ipk: Succeeded
...
NOTE: Running noexec task 1911 of 1931 (/var/jenkins_home/workspace/rs_genivi-dev-platform_PR-9-36W3EOEBNQW3C3NHVVX2BVMRTCK4WU7FZKFC6B42DZI3MMKCMZWQ/gdp-src-build/../poky/meta/recipes-connectivity/dhcp/dhcp_4.3.4.bb:do_build)
...
ERROR: rokers-image-base-1.0-r0 do_rootfs: dhcp not found in the feeds (raspberrypi3 cortexa7t2hf-neon-vfpv4 cortexa7t2hf-neon cortexa7t2hf-vfp cortexa7hf-neon-vfpv4 cortexa7hf-neon cortexa7hf-vfp armv7vet2hf-neon-vfpv4 armv7vehf-neon-vfpv4 armv7vet2hf-neon armv7vehf-neon armv7vet2hf-vfp armv7vehf-vfp armv7at2hf-vfp armv7ahf-vfp armv6thf-vfp armv6hf-vfp armv5tehf-vfp armv5ehf-vfp armv5thf-vfp armv5hf-vfp noarch any all) in /var/jenkins_home/workspace/rs_genivi-dev-platform_PR-9-36W3EOEBNQW3C3NHVVX2BVMRTCK4WU7FZKFC6B42DZI3MMKCMZWQ/gdp-src-build/tmp/deploy/rpm.
ERROR: rokers-image-base-1.0-r0 do_rootfs: This is often caused by an empty package declared in a recipe's PACKAGES variable. (Empty packages are not constructed unless ALLOW_EMPTY_<pkg> = '1' is used.)
ERROR: rokers-image-base-1.0-r0 do_rootfs: Function failed: do_rootfs
ERROR: Logfile of failure stored in: /var/jenkins_home/workspace/rs_genivi-dev-platform_PR-9-36W3EOEBNQW3C3NHVVX2BVMRTCK4WU7FZKFC6B42DZI3MMKCMZWQ/gdp-src-build/tmp/work/raspberrypi3-poky-linux-gnueabi/rokers-image-base/1.0-r0/temp/log.do_rootfs.4343
NOTE: recipe rokers-image-base-1.0-r0: task do_rootfs: Failed
ERROR: Task (/var/jenkins_home/workspace/rs_genivi-dev-platform_PR-9-36W3EOEBNQW3C3NHVVX2BVMRTCK4WU7FZKFC6B42DZI3MMKCMZWQ/gdp-src-build/../meta-rokers/recipes-rokers/images/rokers-image-base.bb:do_rootfs) failed with exit code '1'
NOTE: recipe perl-5.22.1-r0: task do_package_write_ipk: Succeeded
NOTE: Tasks Summary: Attempted 1921 tasks of which 10 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /var/jenkins_home/workspace/rs_genivi-dev-platform_PR-9-36W3EOEBNQW3C3NHVVX2BVMRTCK4WU7FZKFC6B42DZI3MMKCMZWQ/gdp-src-build/../meta-rokers/recipes-rokers/images/rokers-image-base.bb:do_rootfs
Summary: There were 3 WARNING messages shown.
Summary: There were 3 ERROR messages shown, returning a non-zero exit code.
script returned exit code 1
```

**Comment by gmacario** [comment]
Logged as ubuntu@build.rokers.io, log into the easy-jenkins master container:

```
cd ~/github/gmacario/easy-jenkins
docker-compose exec myjenkins /bin/bash
```

Logged as jenkins@container, inspect build logs

```
cd
cat workspace/rs_genivi-dev-platform_PR-9-36W3EOEBNQW3C3NHVVX2BVMRTCK4WU7FZKFC6B42DZI3MMKCMZWQ/gdp-src-build/tmp/work/raspberrypi3-poky-linux-gnueabi/rokers-image-base/1.0-r0/temp/log.do_rootfs.4343
ls -la workspace/rs_genivi-dev-platform_PR-9-36W3EOEBNQW3C3NHVVX2BVMRTCK4WU7FZKFC6B42DZI3MMKCMZWQ/gdp-src-build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/dhcp/4.3.4-r0/packages-split
```

It looks like package `dhcp` is empty, while `dhcp-server` should be the right one to include into the image.

Updated recipe, did a `git commit --amend`, then `git push --force`

**Comment by gmacario** [comment]
Next step: Will test the new image on my RPi3.

**Comment by gmacario** [comment]
Downloading [rokers-image-base-raspberrypi3-20170706155039.rootfs.rpi-sdimg](https://build.rokers.io/job/robotrokers/job/genivi-dev-platform/job/PR-9/3/artifact/gdp-src-build/tmp/deploy/images/raspberrypi3/rokers-image-base-raspberrypi3-20170706155039.rootfs.rpi-sdimg) (252 MB) and writing it to a 8GB microSD-card

**Comment by gmacario** [comment]
- [x] Successfully booted the image on a RPi3.
- [x] Logged to the serial console as user `root` (default password: `root`)
- [x] Inspected local filesystem to verify that package `hostapd` is installed

```
root@raspberrypi3:~# rpm -qil hostapd
Name        : hostapd                      Relocations: (not relocatable)
Version     : 2.5                               Vendor: (none)
Release     : r0                            Build Date: Thu Jul  6 15:19:06 2017
Install Date: Thu Jul  6 15:51:04 2017      Build Host: 16e7a3ddcbbf
Group       : kernel/userland               Source RPM: hostapd-2.5-r0.src.rpm
Size        : 793049                           License: GPLv2 | BSD
Signature   : DSA/SHA1, Thu Jul  6 15:19:06 2017, Key ID 9b1f4a2515f6bedc
Packager    : meta-ivi <genivi-meta-ivi@lists.genivi.org>
URL         : http://w1.fi/hostapd/
Summary     : User space daemon for extended IEEE 802.11 management
Architecture: cortexa7hf_neon_vfpv4
Description :
User space daemon for extended IEEE 802.11 management.
/etc
/etc/hostapd.conf
/lib
/lib/systemd
/lib/systemd/system
/lib/systemd/system/hostapd.service
/usr
/usr/sbin
/usr/sbin/hostapd
/usr/sbin/hostapd_cli
root@raspberrypi3:~# 
```

- [x] Inspected local filesystem to verify that package `dhcp-server` is installed

```
root@raspberrypi3:~# rpm -qil dhcp-server
Name        : dhcp-server                  Relocations: (not relocatable)
Version     : 4.3.4                             Vendor: (none)
Release     : r0                            Build Date: Thu Jul  6 15:19:06 2017
Install Date: Thu Jul  6 15:51:07 2017      Build Host: 16e7a3ddcbbf
Group       : console/network               Source RPM: dhcp-4.3.4-r0.src.rpm
Size        : 2325717                          License: ISC
Signature   : DSA/SHA1, Thu Jul  6 15:19:14 2017, Key ID ac703d5d3fc04d24
Packager    : meta-ivi <genivi-meta-ivi@lists.genivi.org>
URL         : http://www.isc.org/
Summary     : Internet Software Consortium DHCP package
Architecture: cortexa7hf_neon_vfpv4
Description :
DHCP (Dynamic Host Configuration Protocol) is a protocol which allows
individual devices on an IP network to get their own network configuration
information from a server.  DHCP helps make it easier to administer
devices.
/lib
/lib/systemd
/lib/systemd/system
/lib/systemd/system/dhcpd.service
/lib/systemd/system/dhcpd6.service
/usr
/usr/sbin
/usr/sbin/dhcpd
root@raspberrypi3:~#
```

Total number of installed RPM packages:

```
root@raspberrypi3:~# rpm -qa | wc -l
131
root@raspberrypi3:~#
```

Disk space usage on Root FS:

```
root@raspberrypi3:~# df -h /
Filesystem                Size      Used Available Use% Mounted on
/dev/root               197.4M    106.9M     80.2M  57% /
root@raspberrypi3:~#
```

See complete boot log at https://www.dropbox.com/s/ej3wz2a24g0aaw9/20170707-0956-dev-rokers-pull9.txt?dl=0

**Comment by gmacario** [comment]
LGTM, merging PR

**Comment by gmacario** [comment]
@ludusrusso Please review and merge if happy with it

**Comment by gmacario** [comment]
Again, the build failure is due to low disk space on `JENKINS_HOME`

Excerpt from https://build.rokers.io/blue/organizations/jenkins/robotrokers%2Fgenivi-dev-platform/detail/PR-9/4/pipeline

```

WARNING: The free space of /var/jenkins_home/workspace/rs_genivi-dev-platform_PR-9-36W3EOEBNQW3C3NHVVX2BVMRTCK4WU7FZKFC6B42DZI3MMKCMZWQ/gdp-src-build/sstate-cache (/dev/xvdf1) is running low (0.531GB left)
ERROR: No new tasks can be executed since the disk space monitor action is "STOPTASKS"!
WARNING: The free space of /var/jenkins_home/workspace/rs_genivi-dev-platform_PR-9-36W3EOEBNQW3C3NHVVX2BVMRTCK4WU7FZKFC6B42DZI3MMKCMZWQ/gdp-src-build/downloads (/dev/xvdf1) is running low (0.531GB left)
ERROR: No new tasks can be executed since the disk space monitor action is "STOPTASKS"!
WARNING: The free space of /var/jenkins_home/workspace/rs_genivi-dev-platform_PR-9-36W3EOEBNQW3C3NHVVX2BVMRTCK4WU7FZKFC6B42DZI3MMKCMZWQ/gdp-src-build/tmp (/dev/xvdf1) is running low (0.531GB left)
ERROR: No new tasks can be executed since the disk space monitor action is "STOPTASKS"!
NOTE: Tasks Summary: Attempted 723 tasks of which 723 didn't need to be rerun and all succeeded.

Summary: There were 3 WARNING messages shown.
Summary: There were 3 ERROR messages shown, returning a non-zero exit code.
script returned exit code 1
```

Blocker issue tracked as https://github.com/robotrokers/robotrokers.github.io/issues/30

**Comment by ludusrusso** [comment]
tested on @gmacario rasp!

**Pull request merged**
