### PR TITLE
dev-rokers: Add ROS

### PR DESCRIPTION
**Pull request by ludusrusso**
PR equal to #11! Created due to Jekyll issues!

### CODE REVIEW

**Comment by ludusrusso** [comment]
@gmacario it works! :D

**Comment by ludusrusso** [comment]
Tested on qemu! Not properly working:

roscore starts with some warnings (I don't know if it depends from qemu, I'll test it on a real one):
```
# export ROS_ROOT=/opt/ros
# export ROS_DISTRO=indigo
# export ROS_PACKAGE_PATH=/opt/ros/indigo/share
# export PATH=$PATH:/opt/ros/indigo/bin
# export LD_LIBRARY_PATH=/opt/ros/indigo/lib
# export PYTHONPATH=/opt/ros/indigo/lib/python2.7/site-packages
# export ROS_MASTER_URI=http://localhost:11311
# export CMAKE_PREFIX_PATH=/opt/ros/indigo
# touch /opt/ros/indigo/.catkin
# roscore
```

The output is:
```
... logging to /root/.ros/log/88807bf4-634e-11e7-90f3-0242ac110003/roslaunch-1cbcdbbc8141-39.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

Unsupported setsockopt level=270 optname=3
started roslaunch server http://1cbcdbbc8141:41765/
ros_comm version 1.11.21


SUMMARY
========

PARAMETERS
 * /rosdistro: indigo
 * /rosversion: 1.11.21

NODES

...
```

ROSConsole does not work:
```
# rosconsole
```

Output
```
Traceback (most recent call last):
  File "/opt/ros/indigo/bin/rosconsole", line 2, in <module>
    from rospy import rosconsole
  File "/opt/ros/indigo/lib/python2.7/site-packages/rospy/rosconsole.py", line 42, in <module>
    from .logger_level_service_caller import LoggerLevelServiceCaller
  File "/opt/ros/indigo/lib/python2.7/site-packages/rospy/logger_level_service_caller.py", line 34, in <module>
    import rosnode
ImportError: No module named rosnode
```

**Comment by gmacario** [comment]
I tried the image on my Raspberry Pi3 and do not see the error `Unsupported setsockopt level=270 optname=3`

```
root@raspberrypi3:~# export ROS_BOOT=/opt/ros
root@raspberrypi3:~# export ROS_DISTRO=indigo
root@raspberrypi3:~# export ROS_PACKAGE_PATH=/opt/ros/indigo/share
root@raspberrypi3:~# export PATH=$PATH:/opt/ros/indigo/bin
root@raspberrypi3:~# export LD_LIBRARY_PATH=/opt/ros/indigo/lib
root@raspberrypi3:~# export PYTHONPATH=/opt/ros/indigo/lib/python2.7/site-packages
root@raspberrypi3:~# export ROS_MASTER_URI=http://localhost:11311
root@raspberrypi3:~# export CMAKE_PREFIX_PATH=/opt/ros/indigo
root@raspberrypi3:~# touch /opt/ros/indigo/.catkin
root@raspberrypi3:~# roscore
... logging to /home/root/.ros/log/fd162040-6321-11e7-abb3-5fe195ba12f1/roslaunch-raspberrypi3-248.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.
roscore
started roslaunch server http://raspberrypi3:44564/
ros_comm version 1.11.21


SUMMARY
========

PARAMETERS
 * /rosdistro: indigo
 * /rosversion: 1.11.21

NODES

auto-starting new master
process[master]: started with pid [259]
ROS_MASTER_URI=http://raspberrypi3:11311/
roscore http://raspberrypi3:11311/
setting /run_id to fd162040-6321-11e7-abb3-5fe195ba12f1
process[rosout-1]: started with pid [272]
started core service [/rosout]
```

I am a ROS newbie and did not know what to do next, therefore I just typed `^C` and killed `roscore`.

On the other hand I still see the error `ImportError: No module named rosnode` when running `rosconsole`.

Full log: https://www.dropbox.com/s/6yv553zn3alpjjo/20170708-1147-dev-rokers-pull15.txt?dl=0

**Comment by gmacario** [comment]
I believe that in order to fix the `ImportError: No module named rosnode when running rosconsole` you should add the following to https://github.com/ludusrusso/genivi-dev-platform/blob/feat-add-ros/meta-rokers/recipes-rokers/images/rokers-image-base.bb#L32

```
  roslaunch \
  rosnode \
  ...
```

or maybe include `packagegroup-ros-comm` (see https://github.com/bmwcarit/meta-ros/blob/2b7704917c0443183ea1299b15543157fa0c4185/recipes-ros/packagegroups/packagegroup-ros-comm.bb)

**NOTE**: Once we better understand how it works, we might come to the conclusion that https://github.com/bmwcarit/meta-ros/blob/2b7704917c0443183ea1299b15543157fa0c4185/recipes-ros/ros-comm/rosconsole_1.11.21.bb has a bug (failed to list `rosnode` to `RDEPENDS`)

**Comment by ludusrusso** [comment]
Add `packagegroup-ros-comm`. Tested on simulated environment:

 - `roscore` works
 - main ros tools, like `rostopic`, `rosnode`, `rosmsg` work!

Installing now rosserial and rosbridge, to have a super minimum working environment!

**Comment by gmacario** [comment]
Testing https://build.rokers.io/job/robotrokers/job/rokers-yocto-distro/job/PR-16/9/artifact/gdp-src-build/tmp/deploy/images/raspberrypi3/rokers-image-base-raspberrypi3-20170710214354.rootfs.rpi-sdimg on my RPi3.

The image boots, but it does not seem that any ROS services are automatically started. Is this correct?

**NOTE**: This PR increases the size of the target image from  258,048 KB to 454,656 KB - we should probably reconsider which packages we want to include in `rokers-image-base`

**Comment by gmacario** [comment]
@ludusrusso Could you please revert https://github.com/robotrokers/rokers-yocto-distro/pull/16/commits/30b6cc2479c791805372ef54780304f7d4d72bc8 ?

**Comment by ludusrusso** [comment]
Close,  I rebase from `dev-rokers` on #22

**Pull request closed without merging**
