### PR TITLE
dev-robots: Add Jenkinsfile

### PR DESCRIPTION
**Pull request by gmacario**
Add Jenkinsfile for Jenkins pipelines

Slightly adaptated from https://github.com/gmacario/my-genivi-pipelines/tree/build-gdp-master-raspberrypi3

Fix Issue https://github.com/robotrokers/genivi-dev-platform/issues/2

Signed-off-by: Gianpaolo Macario <gmacario@gmail.com>

### CODE REVIEW

**Comment by gmacario** [comment]
@ludusrusso Please Take A Look

**Comment by gmacario** [comment]
Image `core-image-minimal-raspberrypi3-20170627154234.rootfs.rpi-sdimg` generated out of the Jenkins pipeline and successfully tested on a RPi3.

**NOTE**: As the `core-image-minimal` has no networking enabled, in order to get a Linux shell you need to use a USB-to-serial adapter connected to pins 06 (GND), 08 (TXD0), 10 (RXD0) of the Raspberrry Pi 3 GPIO Header. Please see the picture below:

**Comment by gmacario** [comment]
LGTM, merging

**Comment by ludusrusso** [comment]
Ok good! So I cannot test since I've not the adapter at the moment!
I need to buy one! It's not important now to have the HDMI working!

**Comment by ludusrusso** [comment]
Opened #5 as discussed here!

**Pull request merged**
